### ISSUE TITLE
Any plan to release VL-LLaMA and VL-Vicuna?

### ISSUE THREAD

**Issue by Richar-Du** [VPGTrans/VPGTrans#1]
Thanks for your awesome work! Would you mind releasing the checkpoint of VL-LLaMA and VL-Vicuna? I believe the parameter is not very large since the LLM is frozen. Thanks in advance:)

**Comment by waxnkw** [comment]
Thanks for your interest! I have already released them, and written the links in the config file. So, the checkpoints can be automatically downloaded when you run the codes. Of course, you can download them manually. For example, VL-LLaMA can be found [here](https://github.com/VPGTrans/VPGTrans/blob/a2920e6d26160c2872de7edb315130272a129ad6/lavis/projects/blip2/eval/gqa_llama_eval.yaml#L11). VL-Vicuna can be found [here](https://github.com/VPGTrans/VPGTrans/blob/a2920e6d26160c2872de7edb315130272a129ad6/lavis/projects/blip2/demo/vl_vicuna_demo.yaml#L11).

**Comment by Richar-Du** [comment]
Great! Thanks for your reply!
