### ISSUE TITLE
Expected LLaMA 7B folder structure

### ISSUE THREAD

**Issue by HireTheHero** [VPGTrans/VPGTrans#10]
Thanks for your exciting work.

Folder structure for downloaded LLaMA weights looks like the below.
```
<root/folder>
│  tokenizer.model
│  tokenizer_checklist.chk
│
├─7B
│      consolidated.00.pth
│      params.json
│      checklist.chk
├─13B
...
```
However, looks like your codes expect the folder structure and filenames to be more "HuggingFace style".
For example, `tools/linear_proj/train_linear_proj_opt_and_llama.py` reads `AutoTokenizer` from <root/folder>/7B, which requires tokenizer file at 7B sub directory, not <root/folder>. And `LlamaForCausalLM.from_pretrained` calls pretrained model pytorch_model.bin on 7B sub directory.

How can I translate these differences? Once everything is clear, I can raise a small PR for migration. Thanks!

**Comment by waxnkw** [comment]
It seems to be the raw LLaMA weights. You can convert it to huggingface format with this [code](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py). Please refer to the tutorial [here](https://huggingface.co/docs/transformers/main/en/model_doc/llama).

The concrete command will be like:
```bash
python src/transformers/models/llama/convert_llama_weights_to_hf.py \
    --input_dir /path/to/downloaded/llama/weights --model_size 7B --output_dir /output/path
```

**Comment by HireTheHero** [comment]
Thanks! Will take a look and reopen if needed
