### ISSUE TITLE
How to run webui with 13B?

### ISSUE THREAD

**Issue by JavaZeroo** [VPGTrans/VPGTrans#11]
I have done the preparation of the weights, but I found that the config is about 7B
```
./new_lamma/
├── config.json
├── generation_config.json
├── pytorch_model-00001-of-00003.bin
├── pytorch_model-00002-of-00003.bin
├── pytorch_model-00003-of-00003.bin
├── pytorch_model.bin.index.json
├── special_tokens_map.json
├── tokenizer_config.json
├── tokenizer.json
└── tokenizer.model

0 directories, 10 files
```

**Comment by waxnkw** [comment]
Sorry for your problem. Due to the computational resource limitation, I only train a 7B version. If you want to use the 13B version, you can transfer from the 7B version.

**Comment by JavaZeroo** [comment]
I'll give it a try, thank you again for your great work
