### ISSUE TITLE
Size of each datasets

### ISSUE THREAD

**Issue by jonghakim35** [VPGTrans/VPGTrans#13]
Hi, thanks for sharing your work.

I'm wondering if you could provide approximate storage usages of each datasets (COCO, NoCaps, GQA, VG, SBU, and Laion-COCO) in GBs.
It will help me verifying whether if the data is prepared correctly.

**Comment by waxnkw** [comment]
The rough sizes:
    COCO train2014.zip: 13G
    GQA zip file: 21G
    VG zip file: 14G
    SBU zip file: 25G
    Laion-COCO: I use around 400G

**Comment by jonghakim35** [comment]
Hi, thanks for your quick response.
However, while sizes of other datasets approximately match to number you've provided, the size of Laion-COCO differs a lot.

In detail, following instructions in [README](https://github.com/VPGTrans/VPGTrans/blob/main/prepare_data/README.md), I've ran two commands below

```
python download_laion_coco/step1_download_laion_coco_meta.py
bash download_laion_coco/step2_download_laion_coco.sh
```

As a result, I failed in second command due to not enough space left in the disk after downloading about 2.7TB of Laion-COCO dataset.
So I'm wondering

1. Can I know the expected size of Laion-COCO dataset to be initially downloaded? Is it 400GB or much larger (over 2.7TB as far as I observed)?
2. Where does the dataset size of '400GB' comes from? Is it filtered subset of much larger dataset or only 400GB dataset is downloaded initially?

Again, thanks for your response.

**Comment by waxnkw** [comment]
1. You do not need to download the whole Laion-COCO dataset. As for my paper, I only use less than 15M images. You can stop downloading (ctrl+c), when it is roughly 15M images.
2. 15M images takes roughly 400G disk space. I just use the first downloaded 15M images without any filtering.

To count the downloaded images, you can use the following code:
```python
import json
import glob
import sys, os

l = glob.glob(os.path.join(sys.argv[1], "*stats.json")) # sys.argv[1] is the tar files' directory.
n = 0
print(len(l))
for p in l:
    n += json.load(open(p))['successes']
print(n)   
```

**Comment by jonghakim35** [comment]
Thanks for your reply!
