### ISSUE TITLE
What is the normal learning rate?

### ISSUE THREAD

**Issue by byungohko59** [VPGTrans/VPGTrans#16]
Thanks for sharing your work.

I'm curious about the normal learning rate mentioned in Section 3.2, Stage-1, part (c), Warm-up Training.
You mentioned that you trained only the projector for 1 epoch with 5 times of the normal learning rate. 

1) Then, what is the normal learning rate? Is it defined as 'init_lr' or 'warmup_lr' in the config (.yaml) file for training?
2) If the normal learning rate is the learning rate changing from 'init_lr' to 'min_lr' by the scheduler, should I just make the warm-up learning rate 5 times larger?
3) Or should I simply follow your code to reproduce the results reported in your paper?

Thank you for your help!

**Comment by waxnkw** [comment]
1. The normal learning rate is init_lr. BTW, I set the init_lr in some bash file, like the [projector warm-up script](https://github.com/VPGTrans/VPGTrans/blob/32e885cf6907e3c6fb4255b639ea66f36410e56c/run_scripts/blip2/scale_up_train/llama_vpgtrans_step1_proj_warmup.sh#L32). If you need to modify the learning rate, please also check the init_lr in the bash file.
2. Actually, for the projector warm-up, I set the init_lr and min_lr with the same value. Please see the [script](https://github.com/VPGTrans/VPGTrans/blob/32e885cf6907e3c6fb4255b639ea66f36410e56c/run_scripts/blip2/scale_up_train/llama_vpgtrans_step1_proj_warmup.sh#L32).
3. You can follow my code. It is exactly the code I used in my experiments.

**Comment by byungohko59** [comment]
Thanks for your reply!
