### ISSUE TITLE
How many A100(80G) graphics cards are needed to train the model

### ISSUE THREAD

**Issue by liulangjita** [VPGTrans/VPGTrans#3]
Thank you very much for sharing such great job.
How many A100(80G) graphics cards are needed to train the model? Can only one graphics card complete training tasks

**Comment by waxnkw** [comment]
I use 6 or 8 A100-40G for training. The GPU hours for using **1 A100-40G** will be like:

-    BLIP2 OPT2.7B->6.7B: 59.0 hours

-    VL-LLaMA: 67.1 hours

-    BLIP2 FlanT5-XL->XXL: 32.4 hours

- VL-Vicuna is similar to the VL-LLaMA's cost. 

You can divide two to make a rough estimation. If you use one A100(80G), I guess the training time will be less than two days.

BTW, I try to decide the training steps by choosing the data amount to use. I guess 10M is OK for the training. So, if each of your card can hold **b** image-text pairs and you use **n** cards, the steps can be decided by using **10M/n/b**.

**Comment by liulangjita** [comment]
Thank you very much for your quick and detailed reply!
