### ISSUE TITLE
VL-Vicuna Training running program error

### ISSUE THREAD

**Issue by liulangjita** [VPGTrans/VPGTrans#4]
`CUDA_VISIBLE_DEVICES=0 python tools/linear_proj/train_linear_proj_opt_and_llama.py  facebook/opt-6.7b 
./vicuna-7b/  ./blip2_pretrained_opt6.7b.pth   ./lavis/output/proj_init`

running program error

`Traceback (most recent call last):
  File "tools/linear_proj/train_linear_proj_opt_and_llama.py", line 199, in <module>
    model = LinearModel(from_size, to_size)
  File "tools/linear_proj/train_linear_proj_opt_and_llama.py", line 144, in __init__
    super().__init__(from_wrd_model, to_wrd_model)
  File "tools/linear_proj/train_linear_proj_opt_and_llama.py", line 116, in __init__
    to_word_embed_data = get_word_embed(to_wrd_model)
  File "tools/linear_proj/train_linear_proj_opt_and_llama.py", line 110, in get_word_embed
    return word_embed_data
UnboundLocalError: local variable 'word_embed_data' referenced before assignment
`

**Comment by liulangjita** [comment]
I find in function get_word_embed there is not a key word about vicuna. However, there is only keyword opt and llama.

**Comment by waxnkw** [comment]
Sorry for the bug. I have updated the code. Vicuna is instruction-tuned on LLaMA. Thus, the **function with the keyword LLaMA can be directly used for Vicuna**. I just modify this line 105 in `get_word_embed` from `elif "llama" in wrd_model:` to `else:`.

**Comment by liulangjita** [comment]
Thanks. It works
