### ISSUE TITLE
How can I put my custom data into coco dataset?

### ISSUE THREAD

**Issue by liulangjita** [VPGTrans/VPGTrans#5]
I am concerned that the model may not recognize my scene images well. I want put some picture and text pair data into coco dataset, and train them at 1st stage or 2nd stage. However, I find there is a coco_gt dataset when the code runs evaluate. 
Can you tell me which is the best method to put my custom data into the dataset?
Thank you!

**Comment by waxnkw** [comment]
Thanks for the question. I think the coco_gt dataset is mainly for evaluation. If you just want to add the data to the training set, you can go to  `DATADIR/coco/annotations/coco_karpathy_train.json` to append your data items to the json file, and ignore the coco_gt. Do you also want to add your own test test?

**Comment by liulangjita** [comment]
I just want to add the data to the training set. I'll give it a try, thank you
