### ISSUE TITLE
Is the laion_coco dataset is necessary?

### ISSUE THREAD

**Issue by liulangjita** [VPGTrans/VPGTrans#6]
I have downloaded the laion_coco dataset all day long. However, I have not finished the download. Is the laion_coco is necessary? This dataset is too large. Can I just use the coco, vg and sbu dataset at 2nd stage training?

**Comment by waxnkw** [comment]
From my experiments, the Laion_coco is important. It accounts for >1 points for different VQA tasks' performance. But, I think if you have already downloaded a big part like 5M image-text pairs. I guess this might be enough.

To count the downloaded image-text pairs:
``` python
import json
import glob
import sys, os

l = glob.glob(os.path.join(sys.argv[1], "*stats.json")) # sys.argv[1] is the tar files' directory.
n = 0
print(len(l))
for p in l:
    n += json.load(open(p))['successes']
print(n)   
```

**Comment by liulangjita** [comment]
Thank you!
