### ISSUE TITLE
question about sbu dataset

### ISSUE THREAD

**Issue by liulangjita** [VPGTrans/VPGTrans#7]
I encounter such error when loading sbu_caption dataset.
`FileNotFoundError: [Errno 2] No such file or directory: '/root/autodl-tmp/VPG/data/sbu_captions/images/3966232087_47199040c4.jpg'`
I guess that some image tags are in the JSON file, but not in image files . Did you encounter this problem when traing? How did you solve it？
Thank you!

**Comment by waxnkw** [comment]
I just remove the items in the json files that can not be downloaded successfully.
The code may be like:
```python
import os
import json
l = json.load(open("path/to/json"))
l = [x for x in l if os.path.exists(f"/root/autodl-tmp/VPG/data/sbu_captions/images/{x['image']}")]
json.dump(l, open("path/to/json", "w"))
```
