### ISSUE TITLE
Where can I obtain the prompt used?

### ISSUE THREAD

**Issue by likanchuan** [VPGTrans/VPGTrans#9]
Thanks for sharing the awesome work! There is a line: "prompt_path: "prompts/alignment.txt"" in the config of the demo but I did not find the file. Can you help me?

**Comment by waxnkw** [comment]
Does this lead to an error when running the code? I hard code the prompt [here](https://github.com/VPGTrans/VPGTrans/blob/a685f912bb9ebc4079b6eaf31b435927590f45fe/lavis/models/blip2_models/blip2_vicuna.py#L139) and do not use the information contained in "prompts/alignment.txt". If no error, you can just ignore the "prompt_path" item.

If this will cause an error, these are the content in alignment.txt:
```text
<Img><ImageHere></Img> Describe this image in detail.
<Img><ImageHere></Img> Take a look at this image and describe what you notice.
<Img><ImageHere></Img> Please provide a detailed description of the picture.
<Img><ImageHere></Img> Could you describe the contents of this image for me?
```
